### PR TITLE
Add bedrock language data

### PR DESCRIPTION
**Pull request by CreeperG16**
This PR adds language data for bedrock. Each is parsed from `en_US.lang` extracted from vanilla BDS zip's `resource_packs/vanilla/texts` folder. I created a simple script to do this automatically [here](https://github.com/CreeperG16/extract-minecraft-lang/).

### CODE REVIEW

**Comment by CreeperG16** [comment]
Tests are failing as for some reason, some language keys have got `:` characters in them (which the schema does not allow).
- Example: 1.16.201 en_US.lang file:
image

**Comment by CreeperG16** [comment]
Should I add a link to my script in bedrock.md?

**Comment by extremeheat** [comment]
> Should I add a link to my script in bedrock.md?

Yes

**Comment by rom1504** [comment]
will merge once the script is added

**Comment by CreeperG16** [comment]
added

**Pull request merged**
