### PR TITLE
expanded B2J 1.19

### PR DESCRIPTION
**Pull request by Sertonix**
* added missing states to blocksB2J.json
Note: I tried to convert as many blockstates as possible which means that the block might not be the same when converted back

### CODE REVIEW

**Comment by extremeheat** [comment]
Changing the block states is a breaking change. Where did you get that data ? Can you update the extractor ?

**Comment by Sertonix** [comment]
Ok, I double checked and it was an error in mcwiki

**Comment by rom1504** [comment]
will you finish this ?

**Comment by Sertonix** [comment]
This is finished. I can do this for other versions later but not in this pull request.

**Comment by rom1504** [comment]
@extremeheat what do you think about this pr ?

**Comment by RaphiMC** [comment]
I found some invalid block state mappings regarding missing facing values.
Here is an example:
`"minecraft:gray_glazed_terracotta[facing_direction=0]": "minecraft:gray_glazed_terracotta[]",`

Java Edition has no gray_glazed_terracotta without a facing value.
Here is a list of all invalid Java Block states I found: https://pastebin.com/8BMKcxFu

**Comment by rom1504** [comment]
old

**Pull request closed without merging**
