### PR TITLE
Added new field 'description' and blocks metadata

### PR DESCRIPTION
**Pull request by CyberPatrick**
#368

### CODE REVIEW

**Comment by rom1504** [comment]
Where does this data come from ? How can it be used ?

**Comment by CyberPatrick** [comment]
From https://minecraft-ru.gamepedia.com/ and from game, i checked every block. For example of logs, it can help user determine difference between log with 0 and 4 metadata. Due to this change, i can count blocks in area by their displayName.

**Review by rom1504 — APPROVED** [review]

**Comment by u9g** [comment]
shouldn't this be put into all different blocks.json files?

**Comment by rom1504** [comment]
All files before 1.13 maybe yes

**Pull request merged**
