### PR TITLE
Add initial protocol data with login support for 1.19

### PR DESCRIPTION
**Pull request by Moudoux**
Adds the data required for the new login packets in Minecraft 1.19

The protocol.json also contains updated names and packet order, generated with data from wiki.vg. Though, none of the new packets have been implemented, and updates to existing ones have not been implemented either. This PR only focuses on the login stuff.

### CODE REVIEW

**Comment by Moudoux** [comment]
This [commit](https://github.com/mc-oauth/minecraft-data/commit/90ec3d825259808a8acc434130eac7d9acf71ecb) shows the difference between the 1.18 protocol and this

**Comment by rom1504** [comment]
Hey,
Thanks for your contribution!

Can you undo all the packet renames ?
We're trying to keep packet (and field) names stable to maximize compatibility for downstream users

**Comment by rom1504** [comment]
Overall please follow https://github.com/PrismarineJS/minecraft-data/issues/575

**Comment by Moudoux** [comment]
I've updated the PR to remove any changes to the packet names

**Comment by rom1504** [comment]
I think it makes everything much simpler to have a single PR implementing the whole 1.19 protocol changes

This is incomplete

**Comment by rom1504** [comment]
Done now

**Comment by Ege9** [comment]
Hi. Do you know how can i download the console client version which works in 1.19?

**Pull request closed without merging**
