### PR TITLE
Add info about minecraft-data-generator-server to docs

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by AnyBananaGAME** [comment]
oo ty!

**Review by extremeheat — APPROVED** [review]

**Comment by rom1504** [comment]
This is blocked on changing to either
* Remove old and make a table explaining what data the recommended tool produces
* remove new and integrate the recommend tool in the existing table

**Comment by rom1504** [comment]
@wgaylord since you're working actively on the generator, maybe you could update that doc file

**Comment by wgaylord** [comment]
I do have a branch on my fork that I am working on the docs on, going to make a PR with it soon.

**Comment by wgaylord** [comment]
https://github.com/PrismarineJS/minecraft-data/pull/835/

**Pull request closed without merging**
