### PR TITLE
Update to 1.19.3

### PR DESCRIPTION
**Pull request by frej4189**
Protocol serialization is not fully tested. Chat and login works

### CODE REVIEW

**Comment by frej4189** [comment]
Server bound update recipes packet is most likely not properly serialised with this.

**Comment by cmachaca** [comment]
Hi. Why? I am passing the protocol to c++ and I only get 63 at the beginning of the protocol.
```
{
  "1": "game_profile",
  "3": "game_profile",
  "5": "game_profile",
  "7": "game_profile",
  "9": "game_profile",
  "11": "game_profile",
  "13": "game_profile",
  "15": "game_profile",
  "17": "game_profile",
  "19": "game_profile",
  "21": "game_profile",
  "23": "game_profile",
  "25": "game_profile",
  "27": "game_profile",
  "29": "game_profile",
  "31": "game_profile",
  "33": "game_profile",
  "35": "game_profile",
  "37": "game_profile",
  "39": "game_profile",
  "41": "game_profile",
  "43": "game_profile",
  "45": "game_profile",
  "47": "game_profile",
  "49": "game_profile",
  "51": "game_profile",
  "53": "game_profile",
  "55": "game_profile",
  "57": "game_profile",
  "59": "game_profile",
  "61": "game_profile",
  "63": "game_profile"
}
```

**Comment by rom1504** [comment]
looks like your branch is outdated, can you rebase on master ?

**Comment by frej4189** [comment]
> Hi. Why? I am passing the protocol to c++ and I only get 63 at the beginning of the protocol.
> ```
> {
>   "1": "game_profile",
>   "3": "game_profile",
>   "5": "game_profile",
>   "7": "game_profile",
>   "9": "game_profile",
>   "11": "game_profile",
>   "13": "game_profile",
>   "15": "game_profile",
>   "17": "game_profile",
>   "19": "game_profile",
>   "21": "game_profile",
>   "23": "game_profile",
>   "25": "game_profile",
>   "27": "game_profile",
>   "29": "game_profile",
>   "31": "game_profile",
>   "33": "game_profile",
>   "35": "game_profile",
>   "37": "game_profile",
>   "39": "game_profile",
>   "41": "game_profile",
>   "43": "game_profile",
>   "45": "game_profile",
>   "47": "game_profile",
>   "49": "game_profile",
>   "51": "game_profile",
>   "53": "game_profile",
>   "55": "game_profile",
>   "57": "game_profile",
>   "59": "game_profile",
>   "61": "game_profile",
>   "63": "game_profile"
> }
> ```

Because action is a bitfield. If the first bit is set the packet will include game profile data, if the second bit is set the packet will include chat session data. And so on

**Comment by cmachaca** [comment]
> > Hi. Why? I am passing the protocol to c++ and I only get 63 at the beginning of the protocol.
> > ```
> > {
> >   "1": "game_profile",
> >   "3": "game_profile",
> >   "5": "game_profile",
> >   "7": "game_profile",
> >   "9": "game_profile",
> >   "11": "game_profile",
> >   "13": "game_profile",
> >   "15": "game_profile",
> >   "17": "game_profile",
> >   "19": "game_profile",
> >   "21": "game_profile",
> >   "23": "game_profile",
> >   "25": "game_profile",
> >   "27": "game_profile",
> >   "29": "game_profile",
> >   "31": "game_profile",
> >   "33": "game_profile",
> >   "35": "game_profile",
> >   "37": "game_profile",
> >   "39": "game_profile",
> >   "41": "game_profile",
> >   "43": "game_profile",
> >   "45": "game_profile",
> >   "47": "game_profile",
> >   "49": "game_profile",
> >   "51": "game_profile",
> >   "53": "game_profile",
> >   "55": "game_profile",
> >   "57": "game_profile",
> >   "59": "game_profile",
> >   "61": "game_profile",
> >   "63": "game_profile"
> > }
> > ```
> 
> Because action is a bitfield. If the first bit is set the packet will include game profile data, if the second bit is set the packet will include chat session data. And so on

Thanks!!

**Comment by rom1504** [comment]
looks like the commit stack is in a weird state

could you open a clean PR for non protocol and one for protocol

the one for protocol with at least 2 commits
1. the commit of 1.19.2 protocol
2. changes to it

**Comment by rom1504** [comment]
need to be redone

**Pull request closed without merging**
