### PR TITLE
Fix 1.13 enchants and add new 1.16.4 enchants

### PR DESCRIPTION
**Pull request by Karang**
The enchants of 1.13 had wrong ids and some bad names according to https://wiki.vg/index.php?title=Protocol&oldid=14889

New enchants were only added in the 1.16.4 version according to https://wiki.vg/index.php?title=Protocol&oldid=16091 and https://wiki.vg/index.php?title=Protocol&oldid=16317

This PR fix both issues

### CODE REVIEW

**Comment by nickelpro** [comment]
Those ids aren't wrong, they're the NBT ids from 1.13, which were deprecated in subsequent versions. The window IDs are seperate, this was discussed briefly in https://github.com/PrismarineJS/minecraft-data/issues/325.

I think the correct answer requires a schema change, because the NBT ids are important for dealing with world data in 1.13 and the Window IDs are obviously important for correctly interpreting the protocol.

**Comment by Karang** [comment]
> No, the NBT IDs are not used at all in later versions. They only exist in "Fix" classes that map old enchantment data to the new format, for updating existing world files. Soul Speed did not exist in old versions and therefore doesn't even have an ID listed there.

This is what you commented on the issue. If the nbt id is only used for conversions, it should be in a separate data, like what we've done for https://github.com/PrismarineJS/prismarine-schematic/blob/master/lib/legacy.json

Do you know of any place where the id is used and expected to be a nbt id ? We need this changes anyway for the protocol.

**Comment by nickelpro** [comment]
You need both to identify data in <= 1.13.2, because like I said, it's the NBT ID. IE, all slots with an enchanted item, the [optionalNBT field](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.13.2/protocol.json#L32-L70) will identify that enchantment with the NBT id. After 1.13.2 the string ID is used.

**Comment by Karang** [comment]
> You need both to identify enchantment data in <= 1.13.2, because like I said, it's the NBT ID. IE, all slots with an enchanted item, the [optionalNBT field](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.13.2/protocol.json#L32-L70) will identify that enchantment with the NBT id. After 1.13.2 the string ID is used.

I just checked, on 1.13.2 nbt enchant id is a string:
```
// on a book:
client<-server: play.set_slot :{"windowId":0,"slot":38,"item":{"present":true,"itemId":714,"itemCount":1,"nbtData":{"type":"compound","name":"","value":{"StoredEnchantments":{"type":"list","value":{"type":"compound","value":[{"lvl":{"type":"short","value":1},"id":{"type":"string","value":"minecraft:mending"}}]}}}}}}
// on an item:
client<-server: play.set_slot :{"windowId":1,"slot":2,"item":{"present":true,"itemId":786,"itemCount":1,"nbtData":{"type":"compound","name":"","value":{"RepairCost":{"type":"int","value":1},"Enchantments":{"type":"list","value":{"type":"compound","value":[{"lvl":{"type":"short","value":1},"id":{"type":"string","value":"minecraft:mending"}}]}}}}}}
```

**Comment by nickelpro** [comment]
Derp, I'm getting versions mixed up, 1.12.2 was the last version that used enchant IDs. 1.13 was post-flattening and used the string IDs. This should be fine for 1.13 then, but older versions will still be wrong.

**Comment by Karang** [comment]
> Derp, I'm getting versions mixed up, 1.12.2 was the last version that used enchant IDs. 1.13 was post-flattening and used the string IDs. This should be fine for 1.13 then, but older versions will still be wrong.

So its fine, this PR doesn't change data < 1.13

**Comment by nickelpro** [comment]
Yep, ship it. I think it's weird that the meaning of the ID field changes between versions now though. Since Window IDs exist in older versions too, but the ID field now only identifies Window IDs in 1.13.2+

**Comment by rom1504** [comment]
Maybe we can have 2 fields ?
Where do we use this in PrismarineJS modules today ?

**Comment by Karang** [comment]
In 1.12.2, there is no enchant id sent in the window (because the enchantments are hidden it always send -1).

AFAIK the only place where we use enchantments that have a different windowid than their nbt id is in p physics https://github.com/PrismarineJS/prismarine-physics/blob/master/index.js#L634 and we already account for the change from numeric to string.

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
