### PR TITLE
Add 1.14.4 biomes blocks entities items and recipes data

### PR DESCRIPTION
**Pull request by Karang**
1.14.4 data generated with Burger and burger-extractor

### CODE REVIEW

**Comment by rom1504** [comment]
Cool.
You need to change the datapath.json file too for this to work

**Comment by rom1504** [comment]
Did you have to adapt stuff in burger extractor ?
If you did could you also pr these changes ?

**Comment by ImHarvol** [comment]
Every mob has _"Hostile mobs"_ as his category

**Comment by Karang** [comment]
No, I didn't change burger extractor. The only modification I did were manual (2nd commit).
The goal is to provide a base on which to improve, I'm sure there are many mistakes, but having this could already unlock the works on the other packages (prismarine-chunk, mineflayer...)

**Comment by rom1504** [comment]
thanks, released in mcdata 2.47.0

**Pull request merged**
