### PR TITLE
Fix parameter naming inconsistency (#470)

### PR DESCRIPTION
**Pull request by MarsRon**

### CODE REVIEW

**Comment by nickelpro** [comment]
@extremeheat There was a reason this wasn't fixed before but ai don't remember what it was

**Comment by u9g** [comment]
> @extremeheat There was a reason this wasn't fixed before but I don't remember what it was

its a very large change including being breaking

**Comment by rom1504** [comment]
it was blocked by not moving to mcdata (see https://github.com/PrismarineJS/bedrock-protocol/issues/135 )
lgtm, what do you think @extremeheat ?

**Comment by extremeheat** [comment]
It seems to be passing so that’s good, otherwise nothing significant seems to have changed. So far a few people have noticed it, I’m not sure how much of that is through active use vs just good attention to grammar. I’m going to assume it’s mostly the latter, so LGTM.

**Pull request merged**
