### PR TITLE
0.30c blocks.json

### PR DESCRIPTION
**Pull request by mhsjlw**
auto generated

### CODE REVIEW

**Comment by rom1504** [comment]
how did you generate it ?

**Comment by mhsjlw** [comment]
I'll post the script

**Comment by mhsjlw** [comment]
```javascript
const fs = require('fs');

let data = fs.readFileSync('blocks.txt').toString();
let blocks = [];

let regex = /(\d+) (0x\d\w) (.+)/

data.split('\n').forEach(function(line) {
  let exec = regex.exec(line);
  blocks.push({
    "id": parseInt(exec[1]),
    "displayName": exec[3].trim(),
    "name": exec[3].trim().toLowerCase(),
    "hardness": 0,
    "stackSize": 0,
    "diggable": true,
    "boundingBox": "empty",
    "drops": [],
    "transparent": false,
    "emitLight": 0,
    "filterLight": 0
  });
});

fs.writeFileSync('blocks.json', JSON.stringify(blocks, null, 2));

```

`blocks.txt` looks like this:
```
0 0x00 Air
1 0x01 Stone
2 0x02 Grass Block
3 0x03 Dirt
... etc.
```

It is just a direct copy-paste of the wiki

**Comment by rom1504** [comment]
@mhsjlw  do you need me to release a new version of node-minecraft-data including this ?

**Comment by mhsjlw** [comment]
no, i think we're good. i just thought i'd add it.

**Comment by rom1504** [comment]
I released a version with it anyway ;)

**Comment by mhsjlw** [comment]
ah ok :smile:

**Pull request merged**
