### PR TITLE
add 1.10.(1,2)

### PR DESCRIPTION
**Pull request by mhsjlw**

### CODE REVIEW

**Comment by rom1504** [comment]
you need to create the 1.10.1 and 1.10.2 dirs there https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc and just put the version.json file since everything else is the same as 1.10

**Comment by mhsjlw** [comment]
looks good ?

**Comment by rom1504** [comment]
no need for data/pc/1.10.X/protocol.json

**Comment by mhsjlw** [comment]
Got it

**Pull request merged**
