### PR TITLE
fixing version 1.9.2

### PR DESCRIPTION
**Pull request by vimes1984**

### CODE REVIEW

**Comment by rom1504** [comment]
You just copied the 1.9.1-pre2 protocol.json right ?

**Comment by vimes1984** [comment]
yup and swap the 108 to 109

**Comment by rom1504** [comment]
Can you add 1.9.2 at https://github.com/PrismarineJS/minecraft-data/blob/master/data/common/versions.json
and there too https://github.com/PrismarineJS/minecraft-data/blob/master/data/common/protocolVersions.json ?

**Comment by vimes1984** [comment]
there ya go :D

**Pull request merged**
