### PR TITLE
Pc1.20.5 protocol

### PR DESCRIPTION
**Pull request by extremeheat**

### CODE REVIEW

**Comment by extremeheat** [comment]
Extractor is not working correctly per https://github.com/PrismarineJS/minecraft-data-generator-server/issues/23

but i've fixed the issues here manually for now

**Comment by extremeheat** [comment]
There are significant changes to the item encoding which involves removing NBT in favor of custom binary encoded "component" data for items. There is still alot of work to do there and it will require some custom types: for example, in block set (https://wiki.vg/Slot_Data#Block_Set) the length of an array is the value of a field - 1.

Some work was started in this commit to implement the changes https://github.com/PrismarineJS/minecraft-data/pull/898/commits/05a854f6dbd07a493c260653529d088a0fdcfde9

Everything needs to be implemented, as we cannot decode an array of slots without being 100% correct in encode/decode as it will break parsing of all following entries in an array.

**Comment by N4M3L355** [comment]
ping

**Comment by BlockyBlockling** [comment]
> ping

I think @extremeheat is working on this https://github.com/PrismarineJS/minecraft-data-generator-server/pull/25 to then get the Recipe error fixed for all the newer Versions. If you're trying to find out why this has halted.

**Comment by N4M3L355** [comment]
oh hello i didn't know somebody will actually respond, thank everybody for working on this.

**Comment by BlockyBlockling** [comment]
Yeah I'm trying to get to help with this since one month but @extremeheat does not seem to have the time to show the Problems or fix it for now.

**Comment by QvixoteRoux** [comment]
I wanna stay updated for 1.21.x

thanks

**Comment by MightyPiggie** [comment]
> I wanna stay updated for 1.21.x
> 
> thanks

No need to reply. You can just stay updated by clicking the subscribe button.

**Comment by rom1504** [comment]
1 failing

  1) audit recipes pc 1.20.5
       crafting benches has multiple recipes:

      AssertionError [ERR_ASSERTION]: 1 != 1

**Comment by rom1504** [comment]
recipe for crafting table are indeed wrong; missing all the variant wood recipes

still let's not block; will edit the test

**Comment by rom1504** [comment]
#917 for tracking

**Comment by rom1504** [comment]
merging to simplify updates

further fixes can be done in another PR

**Pull request merged**
