### PR TITLE
16w04a update

### PR DESCRIPTION
**Pull request by oldmanmike**
As far as I my eyes can tell, protocol.json is now synced up with the [pre-release protocol page](http://wiki.vg/Pre-release_protocol). This includes the names of the packets so that developers can grep for packets in the json based on the names used on the wiki. Changing packet names might not be desirable for projects directly using protocol.json and are expecting to packets to maintain a stable name, even if the name is out of sync from the wiki. I can switch it back if it turns out to be more trouble than it's worth.

This pull request does not include the reordering of the packets in protocol.json based on packet IDs. This would be quite a bit of work, but it will help readers orient themselves and could result in spotting duplicate packet ID uses.

### CODE REVIEW

**Comment by rom1504** [comment]
Nice!
Indeed I don't think we're ready to use wiki.vg packet names, see that issue https://github.com/PrismarineJS/minecraft-data/issues/27. It would be better to keep that PR as an update to 1.9 and not update the name.

**Comment by rom1504** [comment]
There was some reason for not having packets ordered by packets ids (eg that similar packets (entity packet for example) are kept close), but I think it's probably more trouble than it's worth, and it might be better to reorder them indeed. (but that would be in an other PR)

**Comment by oldmanmike** [comment]
Alright, I'll revert the names.

**Comment by rom1504** [comment]
Alright I tested this with node-minecraft-protocol proxy and there was only one error: held_item_slot is 0x17 not 0x14. That kind of mistake would be easy to spot if packet were in the id order, I think we should move back to that.

**Pull request merged**
