### PR TITLE
Add block_lights.json (1.8 only for now)

### PR DESCRIPTION
**Pull request by hansihe**
Adds block_lights.json which contains data on what blocks emit and filter light. This along with transparency data for each block (not currently in blocks.json, that is another issue) should be enough to calculate lighting in a Minecraft world.

Solves #96.

### CODE REVIEW

**Comment by rom1504** [comment]
we prefer mcdata schemas to be array so that wrapper/reader can index it how they want easily (https://github.com/PrismarineJS/minecraft-data/issues/100)
So I think it would be better to have something like that:
```json
[
{
"blockId":138,
"emitter":15
},
{
"blockId":60,
"filter":15
}
]
```

(you can probably transform your file to look like that automatically)

**Comment by hansihe** [comment]
Right, I wasn't aware any schema was preferred, I should probably have researched a bit more before writing it.

Will make it more like the format you proposed.

**Comment by rom1504** [comment]
would be better to name it `id` than `blockId` actually, since we name it id in other files.

**Comment by rom1504** [comment]
extracted automatically and put in blocks.json in #102

**Pull request closed without merging**
