### PR TITLE
Change has_stack_id in bedrock Item to a boolean

### PR DESCRIPTION
**Pull request by CreeperG16**
Change the type of the `has_stack_id` field in `Item` type for bedrock protocol definition to a boolean type.

### CODE REVIEW

**Comment by extremeheat** [comment]
How do you know this is correct?

**Comment by CreeperG16** [comment]
I double checked locally that true corresponds to a 1 and false corresponds to a 0, other than that it just makes more sense. The field *is* named `has_stack_id` after all. Though if there is a reason why it would be a number, my bad that I didn't find it.

**Review by extremeheat — APPROVED** [review]
Ah, you seem to be correct. I was mistakenly thinking about at the has NBT flag, which is not a boolean.

**Comment by AnyBananaGAME** [comment]
> I double checked locally that true corresponds to a (byte) 1 and false corresponds to a (byte) 0, other than that it just makes more sense. The field *is* named `has_stack_id` after all. Though if there is a reason why it would be a number, my bad that I didn't find it. Though I'd be curious as to what that reason is.

Yea it is

**Comment by AnyBananaGAME** [comment]
I get that with a relay

**Comment by extremeheat** [comment]
After a lot of investigation, this subtle change seems to be breaking Item serialization. I'm not sure why this wasn't caught by the tests, but this breaks the switch check below as it's doing integer comparisons on the boolean. It's possible the switch below can be fixed, but in the meantime I'll revert this PR.

**Pull request merged**
