### PR TITLE
remap u32 to varint in protocol.json

### PR DESCRIPTION
**Pull request by kvoli**
#456 

remove u32 and replace with varint, per every other protocol version.

### CODE REVIEW

**Comment by nickelpro** [comment]
Needs to be double checked with Burger that these snapshots actually don't use u32 here

**Comment by rom1504** [comment]
I don't think this is correct

just add u32 as a native

**Comment by kvoli** [comment]
So all the versions before and after which are varint for that packet, are wrong?

**Comment by nickelpro** [comment]
No, likely it only changed for these versions

**Comment by rom1504** [comment]
> So all the versions before and after which are varint for that packet, are wrong?

looks like this packet was created in the versions in this PR. Can you find any previous version that contains this packet ?

**Comment by nickelpro** [comment]
Looking at the decompile for 17w18a, this was an i32. The correct answer is to just switch to i32 which will fix the issue

**Comment by kvoli** [comment]
Updated with i32 @nickelpro @rom1504

**Review by nickelpro — APPROVED** [review]
LGTM

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
