### PR TITLE
1.19.3 data

### PR DESCRIPTION
**Pull request by frej4189**
- Add data files for 1.19.3 (excluding protocol)
- Update data paths to include 1.19.3
- Update pc/common/versions.json to include 1.19.3
- Add 1.19.3 to README

### CODE REVIEW

**Comment by rom1504** [comment]
CI is failing, can you fix it ?

What did you use to extract the data ?

**Comment by frej4189** [comment]
> CI is failing, can you fix it ?
> 
> What did you use to extract the data ?

CI is failing because protocol.json is not present in this PR. Data is extracted by https://github.com/vadimpronin

**Comment by rom1504** [comment]
> CI is failing because protocol.json is not present in this PR.

let's make it point to 1.19.2 for now

**Comment by rom1504** [comment]
> Data is extracted by https://github.com/vadimpronin

seems like wrong copy/paste, did you mean some other link ?

**Comment by frej4189** [comment]
> > Data is extracted by https://github.com/vadimpronin
> 
> seems like wrong copy/paste, did you mean some other link ?

No. That is the user who provided the data. I didn't extract it myself

**Comment by rom1504** [comment]
@vadimpronin how did you extract the data ?

**Comment by rom1504** [comment]
I want to have the information in the PR discussion for reference, in case we need to understand it later

**Comment by frej4189** [comment]
https://github.com/PrismarineJS/minecraft-data/pull/661/commits/a65dd2b7dd25faf911c361a7c338363bd310c6dc for reference

**Comment by rom1504** [comment]
ok looks like it's this https://github.com/PrismarineJS/minecraft-data-generator-server
which is indeed the recommended tool

**Pull request merged**
