### PR TITLE
1.18.2

### PR DESCRIPTION
**Pull request by nickelpro**
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-18-2
https://wiki.vg/index.php?title=Protocol&diff=17350&oldid=17341

From MCD's point of view this is a minor protocol update

### CODE REVIEW

**Comment by IceTank** [comment]
LGTM

**Comment by rom1504** [comment]
Can you update the readme

**Comment by rom1504** [comment]
And https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/versions.json

**Comment by rom1504** [comment]
And check the previous similar PR if any other file is needed

**Comment by nickelpro** [comment]
I knew I was forgetting a file

**Comment by nickelpro** [comment]
Fixed, minor update 1.16.4 for comparison: https://github.com/PrismarineJS/minecraft-data/commit/8fc974761845d5a385c9a08caa16c091abd9e886

**Pull request merged**
