### PR TITLE
Add 1.17.1 protocol.json

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
something I did notice whiel working on this is that in the window_click packet, mode is a varint, not a byte, and has been for a while, I don't know if it's worth changing the past protocol.jsons, but for this one I made the switch

**Comment by rom1504** [comment]
what's the source of the info ? looks like wiki.vg is not up to date ?

**Comment by u9g** [comment]
> what's the source of the info ? looks like wiki.vg is not up to date ?

I diff’d the minecraft versions by hand, then was going to add the data to wiki if it’s right. I’m not sure who usually adds to the wiki but its been a couple days and 1.17.1 support is already in a lot of big mc projects so would be good to atleast get experimental support here

**Comment by rom1504** [comment]
ok can you add the version file and update the file in common ? (check similar Prs for details)

**Comment by u9g** [comment]
> ok can you add the version file and update the file in common ? (check similar Prs for details)

Done

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/versions.json

**Comment by u9g** [comment]
> https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/versions.json

done

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
