### PR TITLE
Add data

### PR DESCRIPTION
**Pull request by rom1504bot**
Auto-generated by a GH workflow

### CODE REVIEW

**Comment by u9g** [comment]
changes in `tints.json` -> we now can find tint of all biomes, as opposed to before where biomes we didnt find had a 0 for color
changes in `materials.json` -> reordering
changes in `language.json` -> reordering
changes in `entities.json` -> added categories
changes in `effects.json` -> all effects are now lowercased
changes in `blocks.json` -> hardness and resistance always have a decimal even if the decimal is 0
changes in `items.json` -> use correct displayNames + add air to lookup table

**Comment by rom1504** [comment]
looks ok

can you say how you generated it ?

**Comment by u9g** [comment]
copied from discord: I updated prismarine-data-auto-updater to use: https://github.com/u9g/minecraft-data-generator-server

**Comment by rom1504** [comment]
This isn't ready

**Comment by rom1504** [comment]
re open if you want to work on it @u9g

**Pull request closed without merging**
