### PR TITLE
Update Steve Skin for Bedrock

### PR DESCRIPTION
**Pull request by yowzaoppo**
This new Steve skin is better because the other Steve skin had outdated skin information.

### CODE REVIEW

**Comment by yowzaoppo** [comment]
Any updates on this? I updated the title for more context by the way. Just checking in

**Comment by extremeheat** [comment]
Can you update the dataPaths file?

**Comment by yowzaoppo** [comment]
Done.

**Comment by yowzaoppo** [comment]
Let me know of any other issues and such. Otherwise this should be good to go now.

**Review by extremeheat — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
