### PR TITLE
Bedrock 1.19.81

### PR DESCRIPTION
**Pull request by hvlxh**

### CODE REVIEW

**Comment by extremeheat** [comment]
Why the change here?

**Comment by hvlxh** [comment]
i thought it gonna update documention

**Comment by hvlxh** [comment]
because there is no types

**Comment by hvlxh** [comment]
i didn't notice "gh-pages" branch is exists...

**Comment by extremeheat** [comment]
There are no data changes in bedrock 1.19.81 beyond internal fixes, so no change in mc-data is necessary. The pages build is failing, but that will require a separate PR to fix.

**Pull request closed without merging**
