### PR TITLE
Correct the packet mapping

### PR DESCRIPTION
**Pull request by Tracreed**
The packet names were switched for the recipe_book and displayed_recipe.

Source: https://wiki.vg/Protocol#Set_Recipe_Book_State

### CODE REVIEW

**Comment by nickelpro** [comment]
If it's wrong here it's almost definitely wrong in 1.17 as well. Both should be fixed.

Once that's done this LGTM

**Comment by Tracreed** [comment]
1.17 is also done now.

**Review by nickelpro — APPROVED** [review]
LGTM

**Review by nickelpro — APPROVED** [review]
I'm nickelpro, and this is [my favorite PR on the Github](https://youtu.be/oDCCKWuW-yc)

**Review by u9g — APPROVED** [review]
LGTM

**Pull request merged**
