### PR TITLE
Add sounds files for majority of versions.

### PR DESCRIPTION
**Pull request by wgaylord**
This adds the Sound ID to Name mapping information requested in #820 which are only needed for 1.9+

This has that information for the majority of the latest of all versions or the newest that the extractor would run on without much trouble. (Having to rewire other parts of the extractor)

Some versions have the lowest and highest minor versions number since the data-extractor was setup for the lowest, and I also wanted to extract the highest version.

The versions are 1.9.4, 1.10.2, 1.11.2, 1.12.2, 1.13.2, 1.14, 1.144, 1.15, 1.15.2, 1.16 (1.16.5 using 1.16 file), 1.17 (1.17.1 using 1.17 file), 1.18 (1.18.2 using 1.18 file), 1.19, 1.19.2, (1.19.4 using 1.19.2 file), 1.20.1 (1.20 using 1.20.1 file), 1.20.2, 1.20.4

This will also most likely require a PR to node-minecraft-data to provide a nice way of accessing this data.

### CODE REVIEW

**Comment by wgaylord** [comment]
Changed to WIP since I have to go thru and check all the different versions, since for example on 1.13 the code uses the exact id out of the registry over the network, while in 1.19 for example that id gets a 1 added to it, which I did not know about.

**Comment by wgaylord** [comment]
Okay looks like 1.19.2+ needs the ID in the registry offset by one in the packet. (looked thru the source of very version 1.9 to 1.20.4 to check.) Every update we should check the source to make sure we still need the offset.

**Comment by rom1504** [comment]
lgtm

**Pull request merged**
