### PR TITLE
Add advancements data

### PR DESCRIPTION
**Pull request by Eejit43**
This PR adds advancement data (automatically generated, based off of #583).

Todo:
– Update README.md
– Add data for other versions

### CODE REVIEW

**Comment by Lianecx** [comment]
I kinda wanna become a contributor here, Any reason why you made a new pr?

**Comment by Lianecx** [comment]
Also, the schema is not under changed files

**Comment by Eejit43** [comment]
> I kinda wanna become a contributor here, Any reason why you made a new pr?

No reason just seeing as it is generated completely differently I thought it would be better to have a separate PR.

**Comment by Eejit43** [comment]
> > > I kinda wanna become a contributor here, Any reason why you made a new pr?
> > 
> > 
> > No reason just seeing as it is generated completely differently I thought it would be better to have a separate PR.
> 
> So I could also just add that updated file to my PR?

I mean you can do that I'm just going to add all data in this PR

**Comment by Eejit43** [comment]
> `id` should be renamed to `name` and `name` to `displayName` to match the other data files right?

`id` is correct, I'll change `name` to `displayName` however

**Comment by Eejit43** [comment]
Alright I've got to go to work, I'll be back in ~3 hours and will make those changes, update the data (and also fix the achievements as I just realized I generated 1.18 achievements instead of 1.19)

**Comment by Lianecx** [comment]
I updated my pull request #583 accordingly

**Comment by Lianecx** [comment]
> > > > I kinda wanna become a contributor here, Any reason why you made a new pr?
> > > 
> > > 
> > > No reason just seeing as it is generated completely differently I thought it would be better to have a separate PR.
> > 
> > 
> > So I could also just add that updated file to my PR?
> 
> I mean you can do that I'm just going to add all data in this PR

Okay thank you! Just trying to improve my github stats 😅

Do you mind sending or linking me your conversion tool so i cal take a look at it?

**Comment by extremeheat** [comment]
You can make a PR/discuss on his branch, it doesn't make sense to have two PRs when only one can be merged

**Comment by Eejit43** [comment]
> > > > > I kinda wanna become a contributor here, Any reason why you made a new pr?
> > > > 
> > > > 
> > > > No reason just seeing as it is generated completely differently I thought it would be better to have a separate PR.
> > > 
> > > 
> > > So I could also just add that updated file to my PR?
> > 
> > 
> > I mean you can do that I'm just going to add all data in this PR
> 
> Okay thank you! Just trying to improve my github stats 😅
> 
> Do you mind sending or linking me your conversion tool so i can take a look at it?

there is no point having multiple PRs for it, I think just keeping this one open would be better (/nm, not mad). I'm going to completely rework the format and add information from the default texture pack so it is more complete.

**Comment by Eejit43** [comment]
changed to a new format, will discuss in Discord about possibly more additions

**Pull request closed without merging**
