### PR TITLE
Fix wrong slot indices in brewing stand window

### PR DESCRIPTION
**Pull request by Gjum**
thanks to @pokechu22 for the images from his clientside mod https://imgur.com/a/jPUs1

### CODE REVIEW

**Comment by rom1504** [comment]
I bet the same is true for 1.9 ?

**Comment by Gjum** [comment]
yup. but the brewing stand changes in 1.9 and I don't know the slot nr of the blaze powder yet.

**Comment by Gjum** [comment]
Also the player inventory gets a new slot. So I think all that 1.9 stuff will be another PR then.

**Comment by rom1504** [comment]
Okay, merging.

**Pull request merged**
