### PR TITLE
fix: dimension is available from 1.16.2

### PR DESCRIPTION
**Pull request by zardoy**
dimension data in the login packet is from 1.18 (pushing fix the external code), however I didn't test it with mineflayer, most probably this needs to updated: https://github.com/PrismarineJS/mineflayer/blob/2ff9919760d714be57dcb678f8ab5ecff69f5fee/lib/plugins/game.js#L55

### CODE REVIEW

**Comment by extremeheat** [comment]
Why would it need to be updated?

**Comment by zardoy** [comment]
> Why would it need to be updated?

Because mineflayer is not the only project using minecraft-data eg this is important for flying-squid and a few other projects

**Comment by extremeheat** [comment]
Yes, I am specifically referring to your comment mentioning
> dimension data in the login packet is from 1.18 (pushing fix the external code), however I didn't test it with mineflayer, most probably this needs to updated: https://github.com/PrismarineJS/mineflayer/blob/2ff9919760d714be57dcb678f8ab5ecff69f5fee/lib/plugins/game.js#L55

Please elaborate on the change needed

**Comment by rom1504** [comment]
Re open if you want to finish it

**Comment by zardoy** [comment]
> Re open if you want to finish it

I won't be able to reopen it if maintainer closes it

**Comment by zardoy** [comment]
@rom1504 has someone ever reopened their pr after you closed it?

**Comment by rom1504** [comment]
You can say to re-open and I will if you want to finish it. Do you ?

**Pull request closed without merging**
