### PR TITLE
Add block collision shapes

### LINKED ISSUE #258: Block Collision Boxes
Minecraft-Data should provide collision box data for each block.

A use case is implementing client physics or server entity pathfinding, for example https://github.com/PrismarineJS/mineflayer/issues/228 or https://github.com/Gjum/Botlin/issues/4.

This might go together with #52 and/or #83 but since the collision box data is so much it might be better to keep it in a separate file.

### PR DESCRIPTION
**Pull request by Gjum**
Closes #258

### CODE REVIEW

**Comment by rom1504** [comment]
Looks pretty good.
Could you please add some information in the readme or an independent file (similar to https://github.com/PrismarineJS/minecraft-data/blob/master/doc/recipes.md) how did you generate that data and how it's meant to be used (in a few lines) ?

**Comment by Gjum** [comment]
@rom1504 I've added some documentation as requested.

**Comment by rom1504** [comment]
Thanks !

**Comment by u9g** [comment]
> How do we extract collisions for 1.17?
> I could do it for 1.17 and send a pull request if you give me some guidance.
> Thanks in advance.

It’s automated, the workflow just needs to be updated to use java 16, which hasnt been done yet

**Pull request merged**
