### PR TITLE
Adding foods

### PR DESCRIPTION
**Pull request by AppDevMichael**
#295 

Added foods

### CODE REVIEW

**Comment by rom1504** [comment]
How do you plan to use it ? If for mineflayer, it would be great to try to extract the same for other versions. You can change the revision in wiki extractor.
Also could you commit your extractor in wiki extractor repo and link it here ?

**Comment by AppDevMichael** [comment]
I there a list of dates or do I have to find the dates for each release?

**Comment by rom1504** [comment]
you can probably find the dates in the wiki

**Comment by Karang** [comment]
> I there a list of dates or do I have to find the dates for each release?

You can probably generate the older versions from the latest ones, by copying data + checking if the item existed (in items.json).
I don't think any food item were removed (only added). And at least for versions >= 1.9 there shouldn't be any change in properties.

**Comment by AppDevMichael** [comment]
https://github.com/PrismarineJS/minecraft-wiki-extractor/pull/33

**Comment by AppDevMichael** [comment]
I'll do it tomorrow

**Comment by rom1504** [comment]
thanks, the next step so this is usable in mineflayer/flying-squid/node is adding the functions to read this in https://github.com/PrismarineJS/node-minecraft-data ; could you do it ?

**Comment by AppDevMichael** [comment]
I will have a look into it, I may not have as much time to do so because of work.

**Comment by rom1504** [comment]
ah items.json of 1.16.1 was apparently removed in this PR and apparently tests didn't catch it

**Pull request merged**
