### PR TITLE
Bedrock 1.19.10 - Fix set_entity_data tick datatype

### PR DESCRIPTION
**Pull request by stevarino**
Found an issue with the set_entity_data packet that was causing packet errors. I think I was looking at the gophertunnel packet struct datatypes when i should have been looking at the marshalling functions for datatypes. :-)

Anyway, tested with a bot and a human player in survival, which seemed to trigger the packet errors from before.

Sample packet: 3700000001000100000000000000

Resolves as:

```
{
    "name": "set_entity_data",
    "params": {
      "runtime_entity_id": "1477",
      "metadata": [
        {
          "key": "flags",
          "type": "long",
          "value": {
            "_value": "72198383066939392",
            "onfire": false,
            "sneaking": false,
            "riding": false,
            "sprinting": false,
            "action": false,
            "invisible": false,
            "tempted": false,
            "inlove": false,
            "saddled": false,
            "powered": false,
            "ignited": false,
            "baby": false,
            "converting": false,
            "critical": false,
            "can_show_nametag": false,
            "always_show_nametag": false,
            "no_ai": false,
            "silent": false,
            "wallclimbing": false,
            "can_climb": false,
            "swimmer": true,
            "can_fly": false,
            "walker": false,
            "resting": false,
            "sitting": false,
            "angry": false,
            "interested": false,
            "charged": false,
            "tamed": false,
            "orphaned": false,
            "leashed": false,
            "sheared": false,
            "gliding": false,
            "elder": false,
            "moving": true,
            "breathing": true,
            "chested": false,
            "stackable": false,
            "showbase": false,
            "rearing": false,
            "vibrating": false,
            "idling": false,
            "evoker_spell": false,
            "charge_attack": false,
            "wasd_controlled": false,
            "can_power_jump": false,
            "linger": false,
            "has_collision": true,
            "affected_by_gravity": false,
            "fire_immune": false,
            "dancing": false,
            "enchanted": false,
            "show_trident_rope": false,
            "container_private": false,
            "transforming": false,
            "spin_attack": false,
            "swimming": true,
            "bribed": false,
            "pregnant": false,
            "laying_egg": false,
            "rider_can_pick": false,
            "transition_sitting": false,
            "eating": false,
            "laying_down": false
          }
        }
      ],
      "tick": "0"
    }
  }
```

### CODE REVIEW

**Comment by extremeheat** [comment]
Looks correct [per gophertunnel](https://github.com/Sandertv/gophertunnel/blob/master/minecraft/protocol/packet/set_actor_data.go#L37). 

Also looks like the YML & JSON are out of sync. This is bad, there needs to be a test to ensure these are synchronized.

**Comment by stevarino** [comment]
Yeah I was surprised about that too. Having the thing that gets edited and the thing that gets run be separate things that require a na ual step between them I'd unfortunate and I agree that some protection needs to be done, either with some test or an automated build process at release.

GitHub ci tests are new to me but I can look into that this weekend, maybe. Beyond that, anything preventing this from being merged and released?

**Comment by extremeheat** [comment]
Fixed that issue, please rebase on master

**Comment by extremeheat** [comment]
Can you backport this change to 1.18.30 & 1.19.1?

**Comment by stevarino** [comment]
Looks like it went all the way back to 1.16.100 so updated them all:

https://github.com/Sandertv/gophertunnel/commit/cc6c432e22be5a7f73024646592f21f8ec678a3d#diff-3f295b10132ab44463f1ec9b9d6599be50e2dc9f424a17217ff00e6575195e66

**Review by extremeheat — APPROVED** [review]

**Comment by extremeheat** [comment]
Thanks!

**Pull request merged**
