### PR TITLE
add features for prismarine chunk

### PR DESCRIPTION
**Pull request by extremeheat**
add some features from prismarine-chunk

### CODE REVIEW

**Comment by extremeheat** [comment]
Could be helpful to replace "versions" field with "versionRange" and add a "versions" with only explicit versions

**Comment by rom1504** [comment]
Ah do you have some case where the version list does not form a single range ?

**Comment by extremeheat** [comment]
I thought pchunk needed it but it seems not, but prismarine-physics does have split ranges in its features.json

**Comment by rom1504** [comment]
I see, seems quite surprising

**Comment by rom1504** [comment]
but yeah we could bring the feature maybe
not 100% sure if it helps though as it seems it's an edge case so maybe it'd be more confusing than helping

**Pull request merged**
