### PR TITLE
1.20.71 release support

### PR DESCRIPTION
**Pull request by Unbreak4ble**
I added this and changed only the game version and protocol version that is 662.

### CODE REVIEW

**Comment by extremeheat** [comment]
Can you finish the PR? We can't merge without actually updating the protocol

**Comment by Unbreak4ble** [comment]
> Can you finish the PR? We can't merge without actually updating the protocol

done.

**Comment by extremeheat** [comment]
There are no protocol changes?

**Comment by Unbreak4ble** [comment]
> There are no protocol changes?

What kind of protocol are we talking about?

**Comment by ATXLtheAxolotl** [comment]
There should be protocol changes; I know for a fact that resource pack info has been changed.

**Comment by Unbreak4ble** [comment]
> There should be protocol changes; I know for a fact that resource pack info has been changed.

Oh. I got it. I can't provide these changes

**Comment by extremeheat** [comment]
Done in #858

**Pull request closed without merging**
