### PR TITLE
1.19.3 protocol

### PR DESCRIPTION
**Pull request by frej4189**
- Update data paths to point 1.19.3 protocol to pc/1.19.3/protocol.json
- Create 1.19.3/protocol.json

### CODE REVIEW

**Comment by rom1504** [comment]
@extremeheat could you please have a look at https://github.com/PrismarineJS/minecraft-data/pull/669/commits/6e7ceb28a4e1b794516981675f8929945c7962c6 ?

**Comment by rom1504** [comment]
@frej4189 did you test this to work ?

**Comment by frej4189** [comment]
> @frej4189 did you test this to work ?

I haven't tested all packets. It can login and chat without issue.

**Comment by rom1504** [comment]
ok let's go and fix later

**Pull request merged**
