### PR TITLE
add treasureOnly, weight, curse, tradeable, discoverable, rem multiplier

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
this doesn't need any info because the newest enchantments.json comes with all this data

**Comment by Karang** [comment]
@u9g it seems like you added an extra out.json. Otherwise, LGTM.

**Review by rom1504 — CHANGES_REQUESTED** [review]
Can you adapt the schema ?
Is this already explained in the extraction guide ?

**Comment by u9g** [comment]
> @u9g it seems like you added an extra out.json. Otherwise, LGTM.

done

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
