### PR TITLE
Fix digging in mineflayer 1.14.4

### PR DESCRIPTION
**Pull request by Karang**
@rom1504 This should fix the digAndBuild test for 1.14.4

### CODE REVIEW

**Comment by rom1504** [comment]
Could you copy to file to the 1.14.4 folder instead ?

**Comment by Karang** [comment]
> Could you copy to file to the 1.14.4 folder instead ?

done

**Comment by rom1504** [comment]
yeah but actually no it's wrong, these item ids changed in 1.14
I'm working on updating this

**Comment by rom1504** [comment]
done in #282

**Pull request closed without merging**
