### PR TITLE
Propagate catgeory, maxLevel

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Review by Karang — APPROVED** [review]

**Comment by rom1504** [comment]
@u9g that looks fine but could you add some notes on how to generate that in guide file in doc ?
It's important that we know how to generate that in the future if you're not available

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md

**Comment by u9g** [comment]
> @u9g that looks fine but could you add some notes on how to generate that in guide file in doc ?
> 
> It's important that we know how to generate that in the future if you're not available

Its not needed, any newer versions that come out, the extractor natively comes with these, this was just to bring the properties to older enchantment.json s

**Comment by rom1504** [comment]
"the extractor" is not documented in this .md file so that's what need to be done

**Pull request merged**
