### PR TITLE
add language files

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
question : 
* should it be called en_us.json ?
* what about all the other languages ?

**Comment by rom1504** [comment]
or should it go to https://github.com/rom1504/minecraft-assets ?
I have no idea

**Comment by roblabla** [comment]
What's the purpose of minecraft-assets compared to minecraft-data ? Couldn't they be fused ?

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/minecraft-data/issues/78

Currently minecraft-assets contain json files to describe models and textures and the corresponding images (straight from the client jar).
That means it's a bit heavy (a few MB) and it contains copyrightly dubious content.

It's probably best to keep the images in a separate repo.

But I guess the content that is transformed a bit and put as json can go to minecraft-data.

Including that language.json file.

**Pull request merged**
