### PR TITLE
node 18

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
idk where is that require-self mention

**Comment by extremeheat** [comment]
it's from node-minecraft-data https://github.com/PrismarineJS/node-minecraft-data/blob/master/package.json#LL13C17-L13C80

None of the prepare scripts seem to need it so it can probably be removed, but the problem maybe it's not installing the devDeps for some reason

**Comment by rom1504** [comment]
we can simply replace require self by self dep
https://github.com/PrismarineJS/node-minecraft-data/pull/286

**Comment by rom1504** [comment]
I don't understand why it fails with `npm ERR! Error: Cannot find module 'json-schema-to-typescript'`

**Comment by rom1504** [comment]
so error here is still `npm ERR! Error: Cannot find module 'json-schema-to-typescript'`

tried various things but nothing helps

any more idea here @extremeheat ?

**Comment by extremeheat** [comment]
Should be fixed, not sure what flow was going on previously

**Comment by rom1504** [comment]
Thanks

**Pull request merged**
