### PR TITLE
Add particles.json for all PC versions

### PR DESCRIPTION
**Pull request by nickelpro**
First part of fixing #316

I think the answer for fixing the protocol is to just to fix the particleData type with appropriate hard coded indexes. It's a one time thing and doesn't add any new complexity to protocol.json

If it's not clear from the files themselves, each string's array index is its particle ID. I wasn't sure if this was better as an array, an object, or if I should ship both. So I stuck with the simplest thing.

### CODE REVIEW

**Comment by rom1504** [comment]
Is there any data available on particles from burger ?
If not I think it would still be better to do an array of {"id": 0, "name": "the name"} to keep the same style as the rest of the Minecraft data files. And could you also add a simple schema file (you can put it in the schema dir), so it can be used to check the consistency of these values? (for future PRs)

**Comment by nickelpro** [comment]
@rom1504 All of this data is from burger https://github.com/Pokechu22/Burger/pull/14

I'll update the schema to and add a schema file as requested

**Comment by rom1504** [comment]
if you make a script to convert from burger format (only if it's a different format), could you put it in https://github.com/PrismarineJS/burger-extractor ?

**Comment by nickelpro** [comment]
Added schema and updated the particles.json files.

I'm unfamiliar with JS workflows and don't have one set up, but I'll try to figure it out tomorrow and get an extractor to burger-extractor. I'm doing a really trivial transformation on Burger's output though, so anyone can feel free to just push it instead of me.

In python:
```Python
def Burger2MCD(in):
  return [{"id": idx, "name": name} for idx, name in enumerate(in)]
```

**Comment by rom1504** [comment]
can you add particles in https://github.com/PrismarineJS/minecraft-data/blob/master/tools/js/test/test.js#L14 so the test will run ?

**Pull request merged**
