### PR TITLE
Add 1.6.4 protocol.json

### PR DESCRIPTION
**Pull request by nickelpro**
Adding this with the idea that if one pre-netty protocol manages to get support, adding more later will be less of an issue.

Documentation for reviewing this commit:
* [Protocol](https://wiki.vg/index.php?title=Protocol&oldid=4899)
* [Data Types](https://wiki.vg/index.php?title=Data_types&oldid=4806)
* [Metadata](https://wiki.vg/index.php?title=Entity_metadata&oldid=4900)
* [Slot Data](https://wiki.vg/index.php?title=Slot_Data&oldid=4753)
* [Object Data](https://wiki.vg/index.php?title=Object_Data&oldid=4754)

Note that this doesn't add support to NMP for 1.6.4 due to two issues:
* No protocol states
* Strings are UTF-16

The latter is something of an issue, since MCD lacks the ability to signify the change in string encoding.

### CODE REVIEW

**Comment by rom1504** [comment]
what do you think about adding a new `encoding` argument to pstring (https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes/utils.md#pstring--counttype-type-count-countable-) and cstring (https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes/primitives.md#cstring--) of protodef that would default to utf8 ?

**Comment by nickelpro** [comment]
Sounds good to me, is that a request for me to make PRs or the associated repos?

**Comment by rom1504** [comment]
yeah that would be great
at least in the spec repo, and possibly in node protodef, the change would be pretty straight forward (changing the hardcoded utf8 string there https://github.com/ProtoDef-io/node-protodef/blob/master/src/datatypes/utils.js#L104 )

**Comment by nickelpro** [comment]
Still tracking on this, just working on other stuff right now:

Work left to do:

- [x] Update ProtoDef to account for string encodings (https://github.com/ProtoDef-io/ProtoDef/pull/43)

- [ ] Update [node-protodef](https://github.com/ProtoDef-io/node-protodef) to use the new format

- [ ] Update MCD to specify UTF-8 for all protocols except 1.6.4

**Comment by rom1504** [comment]
so close from merging

**Comment by rom1504** [comment]
@nickelpro let's finish this when you have time

**Comment by extremeheat** [comment]
string encoding implemented, https://github.com/ProtoDef-io/node-protodef/pull/133

**Comment by rom1504** [comment]
so string encoding is done
this should now work
maybe you'd like to take another look @nickelpro at some point?

**Comment by rom1504** [comment]
nice but too old, please re-open if you feel like it

**Comment by rom1504** [comment]
actually hmm, I like this one, going to keep it open

**Comment by rom1504** [comment]
old, closing

**Comment by brenoxavier** [comment]
I'm trying to continue the work started by this PR, but the test to validate protocol.json is not accepting the cstring or even the "encoding" property in the pstring.

I updated the version of protodef-validator but I was not successful either, does it need any adjustments?

image

**Comment by extremeheat** [comment]
@brenoxavier 

Right, per https://github.com/ProtoDef-io/node-protodef-validator/pull/11 the validator is failing on latest ProtoDef. If you're working on this what you can do is add a 
```js
instance.types.string = 'native'
```

around https://github.com/PrismarineJS/minecraft-data/blob/1c4cacac6874d513e8725833aa53f0772b0e12b7/tools/js/test/test.js#L30 to force the test to pass for now while you work on it

**Pull request closed without merging**
