### PR TITLE
Add 1.21 data (protocol compliant w/ 1.21.1)

### PR DESCRIPTION
**Pull request by GroobleDierne**
I saw someone wanted to use mineflayer for 1.21.0, it costs nothing to add it.

### CODE REVIEW

**Comment by rom1504** [comment]
Did they say why ?

**Comment by GroobleDierne** [comment]
No, but I guess the server for which they are making a bot did not update

**Comment by rom1504** [comment]
Ok please add in readme

**Comment by GroobleDierne** [comment]
done

**Pull request merged**
