### PR TITLE
Fixed a typo in `command_executed` and `player_movement_corrected`

### PR DESCRIPTION
**Pull request by kotinash**

### CODE REVIEW

**Comment by extremeheat** [comment]
Can you run `npm run build` ?

**Comment by kotinash** [comment]
> Can you run `npm run build` ?

I did that, https://github.com/PrismarineJS/minecraft-data/pull/871/commits/33d9cc229fe29e41fb4844a0cd8cf13ba9e44f63

**Comment by extremeheat** [comment]
Fixed, you changed the line endings from LF to CRLF. You may need to change your git client to automatically turn files to LF based on the remote, see https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by extremeheat** [comment]
Thanks

**Pull request merged**
