### PR TITLE
update to protocol 20w13b

### PR DESCRIPTION
**Pull request by sbh1311**
update to protocol 20w13b sorry for having too much commits

### CODE REVIEW

**Comment by sbh1311** [comment]
sorry for too many commits

**Comment by rom1504** [comment]
You duplicated the files, can you keep them only at the right place ?
To then make all this 2 commits, read https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by timmyRS** [comment]
I've fixed this up and squashed it into a single commit to master: https://github.com/PrismarineJS/minecraft-data/commit/58575d2581288d8fb0f7166bdc1259055d067e42

**Comment by sbh1311** [comment]
I gonna resend the pull request in few minutes

**Comment by timmyRS** [comment]
No need to, it's already merged.

**Comment by sbh1311** [comment]
> No need to, it's already merged.

thanks so much! I couldn't make that I got a strange error trying

**Comment by rom1504** [comment]
@timmyRS can you please revert the commit in master ? This hasn't been reviewed and isn't ready to be merged at all ?

@sbh1311 you do need to clean up these commits so it's possible to review

**Comment by timmyRS** [comment]
Seemed good to me, but I've reverted it.

**Comment by rom1504** [comment]
FYI @timmyRS for that kind of (not trivial) changes, it should go through a PR (with review) and be in at least 2 commits : 
* one that add the file without change
* one that make changes
that makes it possible to review

**Comment by rom1504** [comment]
and fyi this is indeed incorrect, you only changed the packet ids, but you also need to take into account all changes from https://wiki.vg/Pre-release_protocol (not entity metadata but everything else yes)

**Comment by sbh1311** [comment]
> and fyi this is indeed incorrect, you only changed the packet ids, but you also need to take into account all changes from https://wiki.vg/Pre-release_protocol (not entity metadata but everything else yes)

ok so should i close this pull request and send a new one when i got it all fixed ?

**Comment by rom1504** [comment]
You can push to this one again (use git push --force after rewriting
History using git rebase -i)

**Comment by sbh1311** [comment]
i gonna close this and reopen a new one later

**Comment by rom1504** [comment]
would be better to lean how to use git instead but it's your choice

**Pull request closed without merging**
