### PR TITLE
Adding blast resistance

### LINKED ISSUE #383: Add BlastResistence to Blocks
Would be good to have blast resistence data for each block

Some data to extract: https://minecraft-el.gamepedia.com/Explosion

### PR DESCRIPTION
**Pull request by Moondarker**
Contains current minecraft-data data merged with burger-extracted blast resistance

Closes #383

### CODE REVIEW

**Comment by Moondarker** [comment]
Gotta note, blast resistance = undefined (values added as 0 in latest commit) correspond very well with hardness = 0 in the same block, and there are _a lot_ of such blocks in 1.16

Example: Dark Oak Stairs
1.15.2: "hardness": 2, "resistance": 3
1.16.2: "hardness": 0, "resistance": 0

What I mean is, something has got to be wrong with the way 1.16 data is extracted

**Comment by rom1504** [comment]
A bug in burger ?

**Comment by rom1504** [comment]
Did you write some kind of merge script to only add properties and not lose the ones you don't extract?

**Comment by Moondarker** [comment]
Yep, automated it with a node script to merge existing minecraft-data with resistance gathered using burger and a powershell script to make it for every major version
Also, this comment https://github.com/PrismarineJS/burger-extractor/pull/13#issuecomment-803546142 seems to be only partially true, minecraft-data for all versions >=1.13 was clearly extracted using burger-extractor, all versions <=1.12 on the other hand I'm not sure about

**Comment by Moondarker** [comment]
Burger output is affected by https://github.com/Pokechu22/Burger/issues/23, will see if I can make a quick workaround for now.

**Comment by Moondarker** [comment]
This is ready for review, I don't think it can get any better for now. Output of Burger was patched using a list of special cases gathered from 1.16 sources
@rom1504, @Karang, the way minecraft-data was compiled desperately needs to be documented, it will become harder to add new data over time if we can't consistently reproduce results. Also, wiki is a nice source, but by no means a reliable one, especially for any version older than the latest one

**Comment by rom1504** [comment]
Ok will check the pr

About doc I completely agree and the easiest way to do this is that each new pr improve the doc a bit.

So can you add to the "add new version" guide in doc folder what you did here to get blast resistance so the next person can redo the same ?

**Comment by Moondarker** [comment]
Yeah, I just need to clean up a little first. Amount of stuff I collected to get correct values is quite big, but it can be compressed substantially

**Comment by Moondarker** [comment]
Actually, just running burger-extractor with https://github.com/PrismarineJS/burger-extractor/pull/13 should do
However, no matter what I do, I cannot reproduce `blocks.json` from `minecraft-data` by running burger-extractor, some step has to already be missing from "add new version" guide.
I can ofc make a mini-guide on how to merge new data with minecraft-data without re-generating files from scratch, but it's all about egg and chicken paradox, and in future it will lead to problems in determining where different pieces of data came from (if everyone will be merging data like that)

**Comment by Moondarker** [comment]
If we, as a species, lose in some aspects to computers - aspect №1 is data processing

What I mean is - documentation is good, but we can:
1. Automate data merging process from different extractors
2. Improve data extraction from game files instead of getting some parts from wiki

Doing at least one thing of listed above will greatly improve data consistency

**Comment by rom1504** [comment]
yes what you are saying has been tried by several people
https://github.com/PrismarineJS/minecraft-data/issues/283 has some information on this
the last tries on this are:
* https://github.com/extremeheat/minecraft-data-extractor
* https://github.com/PrismarineJS/McDataExtracting/issues/4

burger also has the same purpose

this is a big project, but if you feel like it's important, you could try to contribute to one of these efforts.

**Comment by rom1504** [comment]
unless someone decides to spend some serious time on this, we're not going to solve this extractor problem at once

so my suggestion is instead to document what needs doing and improve the extractors as we go

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
