### PR TITLE
Support released 1.12 protocol

### PR DESCRIPTION
**Pull request by jonathanperret**
I copied the `1.12-pre4` protocol, applied the changes described at http://wiki.vg/Protocol_History , then fixed what prevented a simple `mineflayer` client from connecting (or staying connected) to a 1.12 server.

`mineflayer` runs stable here with these changes, but I can't guarantee there isn't a broken packet that I didn't see.

Hope this is helpful.

### CODE REVIEW

**Comment by bluestreek18** [comment]
I had to add references to 1.12 in data.js and one other file to get this to work with your PR when using node-minecraft-protocol.

**Comment by rom1504** [comment]
Ok I'm starting to review this PR.
FYI, I use http://wiki.vg/index.php?title=Pre-release_protocol&action=history to update the protocol.
It would have been more convenient (for a next time), to first to a commit with an unchanged (copied for pre4) protocol.json and then do other commits for changes. That way the diff is easier to read.

I'll make changes if needed then merge.

**Comment by rom1504** [comment]
Nice work !
http://wiki.vg/Protocol#Advancements ; https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.12/protocol.json#L857 is kind of crazy, cool that it works.

**Comment by rom1504** [comment]
@bluestreek18 you can just use mineflayer 2.3.0 now

**Comment by jonathanperret** [comment]
Noted about the missing first commit, I admit it would have been cleaner.

I did consult http://wiki.vg/index.php?title=Pre-release_protocol&action=history as well (and http://wiki.vg/Protocol of course), but did not find it very convenient to find differences between `1.12-pre4` and `1.12`.

Yeah, I'm glad it worked out with the flags, I was worried at first but happy I could get it to work.

Thanks for merging!

**Pull request merged**
