### PR TITLE
Add new types hash, move the states to its own hash

### PR DESCRIPTION
**Pull request by roblabla**

### CODE REVIEW

**Comment by rom1504** [comment]
Ready to merge ?
I'll do the same change to 1.9 and then merge.

**Comment by roblabla** [comment]
Actually don't merge it just yet, I'm going to add Optional in that PR to simplify the 1.9 entityMetadataItem.

**Comment by roblabla** [comment]
EntityMetadataItem in 1.9

```
{
    "entityMetadataItem": [
      "switch",
      {
        "compareTo": "$compareTo",
        "fields": {
          "0": "byte",
          "1": "varint",
          "2": "float",
          "3": "string",
          "4": "string",
          "5": "slot",
          "6": "bool",
          "7": ["container", [
            { "name": "pitch", "type": "float" },
            { "name": "yaw", "type": "float" },
            { "name": "roll", "type": "float" }
          ]]
        },
        "8": "position",
        "9": ["option", "position"],
        "10": "varint",
        "11": ["option", "UUID"]
      }
    ]
}
```

**Comment by rom1504** [comment]
nice

**Comment by rom1504** [comment]
Is this ready to be changed in 1.9 then merged here too ?

**Pull request merged**
