### PR TITLE
Added pitches.json

### PR DESCRIPTION
**Pull request by demipixel**

### CODE REVIEW

**Comment by phase** [comment]
I think "num" sounds a little weird. Maybe something like "id" would be clearer.

**Comment by rom1504** [comment]
It's not id, it's "number of uses", whatever that means http://minecraft.gamepedia.com/Note_Block#Usage

**Comment by Gjum** [comment]
It's how often you click on a noteblock to get that note, so it's kind of an offset or ID. `num` is really ambiguous.

**Comment by rom1504** [comment]
So apparently all this is computable https://www.npmjs.com/search?q=note
pitch = 0.5 * (2^(1/12)) ^ num
octave = floor(num / 12)
num=log(pitch)/log(0.5 *  (2^(1/12)))

http://www.phy.mtu.edu/~suits/NoteFreqCalcs.html

Does that mean we don't need this file or should we keep that file and generate it ?

**Comment by Gjum** [comment]
The only thing of that calculation that is specific to minecraft is the fact that `pitch = 1` means `num = 12` means F# (probably need the absolute pitch somewhere), everything else can be calculated from there.

This means it is possible to have at least that info in minecraft-data and let the wrappers provide conversion functions.

On the other hand, having `pitch`, `num`, and maybe `absolute pitch` in minecraft-data would be OK too, because there are just 25 entries anyway and they represent all the data needed to play noteblock music.

**Comment by demipixel** [comment]
None of this data ever changes so, while it would be convenient to have a generator, it would only ever be used once.

**Comment by Gjum** [comment]
@demipixel that's the exact reason for it to be in a separate package, as it is not minecraft dependent.

**Comment by rom1504** [comment]
@demipixel so do you think we still need this data even though https://github.com/mhsjlw/flying-squid/blob/master/src/lib/serverPlugins/sound.js#L34 works ?

**Comment by demipixel** [comment]
It was just useful to have the keys and stuff, but I can't say it was 100% necessary.

(Although sounds and particles would be nice but that's for another time :3)

**Comment by rom1504** [comment]
So, we didn't need that in flying-squid. And it seems everything there can be computed easily.

Closing, if we happen to need it later, the code will always be there (although it really does seem it's not needed)

**Pull request closed without merging**
